blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
        # post views
        path('', views.post_list, name='post_list'),
        path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
        path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

    ]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:course_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:course_id>/", views.cart_remove, name="cart_remove"),
]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    # post views
    path("", views.course_list, name="course_list"),
    path("<slug:category_slug>", views.course_list, name="course_list_by_category"),
    path("<slug:slug>/", views.course_detail, name="course_detail"),
]

llkanalytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


COURSE_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddCourseForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=COURSE_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from courses.models import Course
from .cart import Cart
from .forms import CartAddCourseForm


@require_POST
def cart_add(request, course_id):
    cart = Cart(request)
    course = get_object_or_404(Course, id=course_id)
    form = CartAddCourseForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            course=course, quantity=cd["quantity"], override_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, course_id):
    cart = Cart(request)
    course = get_object_or_404(Course, id=course_id)
    cart.remove(course)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddCourseForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

templates/cart/detail.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}
{% block title %}
Shopping Cart
{% endblock %}
{% block content %}


<div class="container">
    
    <div class="row">
        <div class="col"><h1>Shopping Cart</h1></div>
    </div>

    {% for item in cart %}
    {% with course=item.course %}
    <div class="row">   
        <div class="col">
            <a href="{{ course.get_absolute_url }}">
                <img style="width: 100px; height: 100px;"  src="{% if course.image %}{{ course.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
        </div>
    <div class="col-6">
        <h4>{{ course.name }}</h4>
        <div class="d-flex">
            <div class="">
                <form action="{% url "cart:cart_add" course.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" value="Update" class="btn btn-primary mx-2">
                    {% csrf_token %}
                </form>
            </div>
            <div class="">
                <form action="{% url "cart:cart_remove" course.id %}"
                method="post">
                <input type="submit" value="Remove" class="btn btn-primary mx-2">
                {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <h6>Price: ${{ item.price }}</h6>
        <h6>Subtotal: ${{ item.total_price }}</h6>
    </div>

        {% endwith %}
        {% endfor %}
    </div>
    <div class="row">
        <div class="col">
            <h4>Total: ${{ cart.get_total_price }}</h4>
            <a href="{% url "courses:course_list" %}" class="btn btn-primary
            light">Continue shopping</a>
            <a href="#" class="btn btn-primary">Checkout</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}