blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
        # post views
        path('', views.post_list, name='post_list'),
        path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
        path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

    ]

llkanalytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/post/includes/comment_form.html
{% load bootstrap5 %}


<div class="d-flex flex-column flex-md-row justify-content-evenly align-items-center py-3">
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
{% bootstrap_form form %}
{% csrf_token %}
<p><input type="submit" value="Add comment" class="btn btn-outline-success"></p>
</form>
</div>