blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
        # post views
        path('', views.post_list, name='post_list'),
        path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
        path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

    ]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    # post views
    path("", views.course_list, name="course_list"),
    path("<slug:category_slug>", views.course_list, name="course_list_by_category"),
    path("<slug:slug>/", views.course_detail, name="course_detail"),
]

llkanalytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "pages"

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path(
        "services/",
        TemplateView.as_view(template_name="services.html"),
        name="services",
    ),
    path("contact/", views.contact, name="contact"),
]

templates/base.html
{% load static %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Blog and Services devoted to Analytics and Data Science">
    <meta name="keywords" content="kadzielawa, llkanalytics, statistics, analysis, machine learning, sql, python">
    <meta name="author" content="Konrad Kadzielawa">
    <meta property="og:site_name" content="LLK Analytics">
    <meta property="og:title" content="LLK Analytics"> 
    <meta property="og:description" content="Blog and Services devoted to Analytics and Data Science">
    <meta property="og:type" content="blog">

    <title>LLK Analytics | Data &amp Analytics | Blog &amp Services</title>
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
  </head>
  <body>
  {% comment %} Navbar {% endcomment %}

  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'pages:home' %}">LLK Analytics</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'pages:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:services' %}">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:course_list' %}">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

    
    <div class="py-2">
      {% block content %} 
      
      {% endblock %}
    </div>

      <footer class="bg-dark d-flex flex-wrap justify-content-between align-items-center py-3">
        <div class="col-md-4 d-flex align-items-center">
          <span class="mb-3 mb-md-0 text-light">© 2024 LLKAnalytics</span>
        </div>
    
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3 mx-2 "><a class="text-light" href="https://www.linkedin.com/in/konradkadzielawa/"><i class="fab fa-linkedin-in fa-x"></i></a></li>
          <li class="ms-3 mx-2 "><a class="text-light" href="https://www.youtube.com/channel/UChqPSa40XJxfD2NYq7H9Vsw"><i class="fab fa-youtube fa-x"></i></a></li>
          <li class="ms-3 mx-2 "><a class="text-light" href="https://twitter.com/kkadzielawa"><i class="fab fa-twitter fa-x"></i></a></li>
        </ul>
      </footer> 
    <script src="https://kit.fontawesome.com/6e526d197e.js" crossorigin="anonymous"></script>
  </body>

</html>

templates/contact.html
{% extends "base.html" %} 
{% load bootstrap5 %}

{% block content %}






{% if sent %}
<h1>E-mail successfully sent</h1>
{% else %}
<div class="d-flex flex-column flex-md-row justify-content-evenly align-items-center py-3">
<h2>Shoot Me a Message!</h2>
<form method="post">
{% csrf_token %}
{% bootstrap_form form %}

<input type="submit" class="btn btn-outline-success" value="Send">

</form>
{% endif %}

</div>

{% endblock %}

templates/home.html
{% extends "base.html" %} 

{% load static %}

{% load bootstrap5 %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-lg-between align-items-center">
        <div id="personal-photo-div" class="col-md p-4 text-align-center">
            <img src="{% static 'img/personal_photo.png' %}" alt="" srcset="">
        </div>
        <div class="col-md p-4">
            <p class="">
                Hi! My name is Konrad Kadzielawa and I am a Chicago-based data analytics professional. <br>
                I have been involved in a variety of analytics-related professions ever since I started professional work. <br>
                This site is centered on the blog section where I intend to regularly post information relevant to analytics/data science and how it can impact your business. <br>
                I also offer services related to analytics - more available in the Services section of this website. Lastly, please click on the contact section to contact me with relevant inquiries. <br><br>
                Thank you!
            </p>
        </div>
    </div>
</div>
{% endblock %}

templates/services.html
{% extends "base.html" %} 

{% block content %}

<p>List of relevant services...</p>

{% endblock %}