blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
        # post views
        path('', views.post_list, name='post_list'),
        path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
        path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

    ]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:course_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:course_id>/", views.cart_remove, name="cart_remove"),
]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    # post views
    path("", views.course_list, name="course_list"),
    path("<slug:category_slug>", views.course_list, name="course_list_by_category"),
    path("<slug:slug>/", views.course_detail, name="course_detail"),
]

llkanalytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.urls import reverse


# Categories
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [models.Index(fields=["name"])]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:course_list_by_category", args=[self.slug])


# Courses
class Course(models.Model):
    category = models.ForeignKey(
        Category, related_name="courses", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to="courses/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:course_detail", args=[self.slug])

courses/views.py
from django.shortcuts import render, get_object_or_404


from .models import Category
from .models import Course

from cart.forms import CartAddCourseForm


def course_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    courses = Course.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(
            Category,
            slug=category_slug,
        )
        courses = Course.objects.filter(category=category)
    return render(
        request,
        "courses/list.html",
        {"category": category, "categories": categories, "courses": courses},
    )


def course_detail(request, slug):
    course = get_object_or_404(Course, slug=slug, available=True)

    cart_course_form = CartAddCourseForm()

    return render(
        request,
        "courses/detail.html",
        {"course": course, "cart_course_form": cart_course_form},
    )

templates/courses/detail.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}



{% block title %}
{{ course.name }}
{% endblock %}

{% block content %}
<div class="course-detail">
<a href="{% url 'courses:course_list' %}">Courses</a>
</br>
<a href="{{ course.category.get_absolute_url }}">{{ course.category }}</a>
</br>
<img style="width: 100px; height: 100px;" src="{% if course.image %}{{ course.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ course.name }}</h1>
<h2>

{{ course.category }}
</a>
</h2>
<p class="price">${{ course.price }}</p>
{{ course.description|linebreaks }}
</div>
<form action="{% url "cart:cart_add" course.id %}" method="post">
    {{ cart_course_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>
{% endblock %}

templates/courses/list.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}


{% block title %}
{% if category %}{{ category.name }}{% else %}Courses{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Categories</h3>
<ul class="list-group">

<li {% if not category %} {% endif %}>
<a href="{% url "courses:course_list" %}">All</a>
</li> 
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected"
{% endif %}>
<a href="{{c.get_absolute_url}}">{{ c.name }}</a> 
</li>
{% endfor %} 
</ul>

</div>
 <div id="main" class="course-list">
<h1>{% if category %}{{ category.name }}{% else %}Courses
{% endif %}</h1>
{% for course in courses %}
{{course}}
<div class="item">
<a href="{{ course.get_absolute_url }}">
<img style="width: 100px; height: 100px;" src="{% if course.image %}{{ course.image.url }}{% else %}{%
static "img/no_image.png" %}{% endif %}">
</a>
<br>
<a href="{{ course.get_absolute_url }}">{{ course.name }}</a>
<br>
${{ course.price }}
</div>
{% endfor %}
</div> 

<h2><a href="{% url 'cart:cart_detail' %}">Shopping Cart</a></h2>
{% endblock %}